### DISCUSSION TITLE
Deploying API in windows environment: Links not correct

### DISCUSSION THREAD

**Discussion by ianhorn** [stac-utils/stac-fastapi-pgstac#199] [General]
I have created windows servercore-ltsc images for the stac-fastapi and pgstac repos (this is the environment I have to work with - can't get linux images to work without hyper-v).  I was succesful in making the API work in a windows vm, but the Link URLs are not generating properly.  The <domainname>/stac-api works fine, and you can navigate through the stac if you just change the domain name.  Otherwise, in the link section, all the URLs are still *http://localhost:8082/<%>*. 

I created a reverse proxy with IIS and I don't think IIS is the problem - I could be wrong. Is there a setting in the Dockerfile/docker-compose/app.py/.env that I need to declare? 

```json
  "links": [
    {
      "rel": "self",
      "type": "application/json",
      "href": "http://localhost:8082/"
    },
    {
      "rel": "root",
      "type": "application/json",
      "href": "http://localhost:8082/"
    },
    {
      "rel": "data",
      "type": "application/json",
      "href": "http://localhost:8082/collections"
    },
    {
      "rel": "conformance",
      "type": "application/json",
      "title": "STAC/OGC conformance classes implemented by this server",
      "href": "http://localhost:8082/conformance"
    },
    {
      "rel": "search",
      "type": "application/geo+json",
      "title": "STAC search",
      "href": "http://localhost:8082/search",
      "method": "GET"
    },
    {
      "rel": "search",
      "type": "application/geo+json",
      "title": "STAC search",
      "href": "http://localhost:8082/search",
      "method": "POST"
    },
```

```yaml
services:
  app:
    container_name: stac-fastapi-pgstac
    image: ianhorn/stac-fastapi-pgstac:1.0.1
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}

      - STAC_FASTAPI_TITLE=${STAC_FASTAPI_TITLE}
      - STAC_FASTAPI_DESCRIPTION=${STAC_FASTAPI_DESCRIPTION}
      - STAC_FASTAPI_LANDING_ID=${STAC_FASTAPI_LANDING_ID}
    ports:
      - "8082:8082"
    # volumes:
    #   - /app:/app
    depends_on:
      - database
    command: bash -c "./scripts/wait-for-it.sh database:5432 && python -m stac_fastapi.pgstac.app"
```
